# Generated by Django 5.1.1 on 2024-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
